/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/detection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detection View
         * @description Which stores detect and block the bot, across every run.
         */
        get: operations["detection_view_api_detection_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Discovery
         * @description Find stores, then start a run on all of them; poll GET /api/discover/{id}.
         */
        post: operations["start_discovery_api_discover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discover/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Discover Options
         * @description What the interface offers for finding stores, and which sources have a key.
         *     Keys themselves are never sent.
         */
        get: operations["discover_options_api_discover_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discover/{discovery_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Discovery */
        get: operations["discovery_api_discover__discovery_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Llm Check
         * @description Prove a key and model work before a run (PRD LM-05).
         */
        post: operations["llm_check_api_llm_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Llm Providers
         * @description The supported providers (PRD LM-02) and whether .env already has a key for each.
         *     Keys themselves are never sent.
         */
        get: operations["llm_providers_api_llm_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Options */
        get: operations["options_api_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview */
        post: operations["preview_api_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs */
        get: operations["runs_api_runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Detail */
        get: operations["run_detail_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/download/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download */
        get: operations["download_api_runs__run_id__download__key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Events
         * @description Server-sent events: the full run state each time it changes, until it ends.
         */
        get: operations["run_events_api_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume Run
         * @description Continue a stopped or interrupted run without revisiting finished stores.
         */
        post: operations["resume_run_api_runs__run_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/rows/{table}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rows */
        get: operations["rows_api_runs__run_id__rows__table__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop Run
         * @description Finish the stores in progress, start no new ones; the run stays resumable.
         */
        post: operations["stop_run_api_runs__run_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/traffic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Traffic View
         * @description Sessions on our own Shopify store, from Shopify Analytics (ADR 0009). Answers are
         *     cached, so polling this every few seconds costs no extra Shopify quota.
         */
        get: operations["traffic_view_api_traffic_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload */
        post: operations["upload_api_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BlockedStoreOut */
        BlockedStoreOut: {
            /** Blocked */
            blocked: number;
            /** Domain */
            domain: string;
            /** Last Method */
            last_method: string;
            /** Last Run Id */
            last_run_id: string;
            /** Last Seen */
            last_seen: string;
            /** Platform */
            platform: string;
            /**
             * State
             * @enum {string}
             */
            state: "always" | "sometimes" | "recovered";
            /** Visits */
            visits: number;
        };
        /** Body_upload_api_uploads_post */
        Body_upload_api_uploads_post: {
            /** File */
            file: string;
        };
        /**
         * DetectionOut
         * @description How often stores detect and block the bot, across every run on disk.
         */
        DetectionOut: {
            /** Blocked */
            blocked: number;
            /** Blocked Stores */
            blocked_stores: components["schemas"]["BlockedStoreOut"][];
            /** By Method */
            by_method: {
                [key: string]: number;
            };
            /** Runs */
            runs: components["schemas"]["DetectionRunOut"][];
            /** Stores */
            stores: number;
            /** Stores Blocked */
            stores_blocked: number;
            /** Visits */
            visits: number;
        };
        /** DetectionRunOut */
        DetectionRunOut: {
            /** Blocked */
            blocked: number;
            /** Run Id */
            run_id: string;
            /** Started At */
            started_at: string;
            /** Visits */
            visits: number;
        };
        /**
         * DiscoverIn
         * @description Find stores, then start a run on them (ADR 0008).
         */
        DiscoverIn: {
            /** Count */
            count: number;
            /** Items */
            items: string[];
            /** Region */
            region: string;
            /** Terms */
            terms?: string[];
            /** Writers */
            writers: string[];
        };
        /** DiscoverOptionsOut */
        DiscoverOptionsOut: {
            /** Agent Model */
            agent_model: string;
            /** Default Items */
            default_items: string[];
            /** Default Region */
            default_region: string;
            /** Items */
            items: string[];
            /** Max Count */
            max_count: number;
            /** Regions */
            regions: string[];
            /** Sources */
            sources: {
                [key: string]: boolean;
            };
        };
        /** DiscoveryOut */
        DiscoveryOut: {
            /** Cost Usd */
            cost_usd: number;
            /** Count */
            count: number;
            /** Discovery Id */
            discovery_id: string;
            /** Error */
            error: string;
            /** Found */
            found: number;
            /** Run Id */
            run_id: string | null;
            /** Sources */
            sources: components["schemas"]["DiscoverySourceOut"][];
            /**
             * State
             * @enum {string}
             */
            state: "searching" | "starting_run" | "done" | "failed";
            /** Step */
            step: string;
            /** Stores To Visit */
            stores_to_visit: number;
        };
        /** DiscoverySourceOut */
        DiscoverySourceOut: {
            /** Error */
            error: string;
            /** Found */
            found: number;
            /** Name */
            name: string;
            /** Status */
            status: string;
        };
        /** DownloadOut */
        DownloadOut: {
            /** Filename */
            filename: string;
            /** Key */
            key: string;
            /** Label */
            label: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LLMCheckIn */
        LLMCheckIn: {
            /** Api Base */
            api_base?: string | null;
            /** Api Key */
            api_key?: string | null;
            /** Model */
            model: string;
        };
        /** LLMCheckOut */
        LLMCheckOut: {
            /** Message */
            message: string;
            /** Ok */
            ok: boolean;
        };
        /**
         * LLMIn
         * @description LLM settings for one run. The key stays in memory for this run only (PRD LM-04).
         */
        LLMIn: {
            /** Api Base */
            api_base?: string | null;
            /** Api Key */
            api_key?: string | null;
            /**
             * Budget Usd
             * @default 1
             */
            budget_usd: number;
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /** Fallbacks */
            fallbacks?: string[];
            /**
             * Model
             * @default
             */
            model: string;
        };
        /** OptionsOut */
        OptionsOut: {
            /** Default Writers */
            default_writers: string[];
            /** Max Links */
            max_links: number;
            /** Max Upload Mb */
            max_upload_mb: number;
            /** Suffixes */
            suffixes: string[];
            /** Writers */
            writers: string[];
        };
        /** OverviewOut */
        OverviewOut: {
            /** Contacts */
            contacts: number;
            last_run: components["schemas"]["RunListItem"] | null;
            /** Products */
            products: number;
            /** Runs */
            runs: number;
            /** Runs Done */
            runs_done: number;
            /** Stores */
            stores: number;
        };
        /** PreviewIn */
        PreviewIn: {
            source: components["schemas"]["SourceIn"];
            /**
             * Url Column
             * @default auto
             */
            url_column: string;
        };
        /** PreviewOut */
        PreviewOut: {
            /** Duplicates */
            duplicates: number;
            /** Links */
            links: number;
            /** Max Links */
            max_links: number;
            /** Skipped */
            skipped: {
                [key: string]: number;
            };
            /** Skipped Examples */
            skipped_examples: components["schemas"]["SkippedLink"][];
            /** Store Examples */
            store_examples: string[];
            /** Stores */
            stores: number;
            /** Too Many */
            too_many: boolean;
        };
        /** ProviderOut */
        ProviderOut: {
            /** Example Model */
            example_model: string;
            /** Key In Env */
            key_in_env: boolean;
            /** Label */
            label: string;
            /** Needs Key */
            needs_key: boolean;
            /** Provider */
            provider: string;
        };
        /**
         * RowsOut
         * @description A page of one table's rows, for previewing data in the interface.
         */
        RowsOut: {
            /** Columns */
            columns: string[];
            /** Offset */
            offset: number;
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
            /** Table */
            table: string;
            /** Total */
            total: number;
            /** Truncated Fields */
            truncated_fields: boolean;
        };
        /** RunIn */
        RunIn: {
            llm?: components["schemas"]["LLMIn"] | null;
            source: components["schemas"]["SourceIn"];
            /**
             * Url Column
             * @default auto
             */
            url_column: string;
            /** Writers */
            writers: string[];
        };
        /** RunListItem */
        RunListItem: {
            /** Contacts */
            contacts: number;
            /** Links In */
            links_in: number;
            /**
             * Mode
             * @enum {string}
             */
            mode: "test" | "full";
            /** Products */
            products: number;
            /** Run Id */
            run_id: string;
            /** Source Name */
            source_name: string;
            /** Started At */
            started_at: string;
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "running" | "stopped" | "done" | "failed" | "interrupted";
            /** Stores Done */
            stores_done: number;
            /** Stores Total */
            stores_total: number;
        };
        /** RunOut */
        RunOut: {
            /** Cli */
            cli: string;
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Contacts */
            contacts: number;
            /** Downloads */
            downloads: components["schemas"]["DownloadOut"][];
            /** Error */
            error: string;
            /** Final Products */
            final_products: number;
            /** Final Stores */
            final_stores: number;
            /** Finished At */
            finished_at: string;
            /** Knit Products */
            knit_products: number;
            /** Limit */
            limit: number | null;
            /** Links In */
            links_in: number;
            /** Llm Cost Usd */
            llm_cost_usd: number;
            /** Llm Model */
            llm_model: string;
            /** Llm Stores */
            llm_stores: number;
            /**
             * Mode
             * @enum {string}
             */
            mode: "test" | "full";
            /** Pages */
            pages: number;
            /** Processed */
            processed: number;
            /** Products */
            products: number;
            /** Run Id */
            run_id: string;
            /** Skipped */
            skipped: number;
            /** Skipped By Reason */
            skipped_by_reason: {
                [key: string]: number;
            };
            /**
             * Source Kind
             * @enum {string}
             */
            source_kind: "text" | "file";
            /** Source Name */
            source_name: string;
            /** Started At */
            started_at: string;
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "running" | "stopped" | "done" | "failed" | "interrupted";
            /** Status Counts */
            status_counts: {
                [key: string]: number;
            };
            /** Stores */
            stores: components["schemas"]["StoreOut"][];
            /** Stores Done */
            stores_done: number;
            /** Stores Total */
            stores_total: number;
            /** Writers */
            writers: string[];
        };
        /** SkippedLink */
        SkippedLink: {
            /** Raw */
            raw: string;
            /** Reason */
            reason: string;
        };
        /**
         * SourceIn
         * @description Exactly one of pasted text or a previously uploaded file.
         */
        SourceIn: {
            /** Text */
            text?: string | null;
            /** Upload Id */
            upload_id?: string | null;
        };
        /** StoreOut */
        StoreOut: {
            /** Contact Count */
            contact_count: number;
            /** Currency */
            currency: string;
            /** Domain */
            domain: string;
            /** Error */
            error: string;
            /** Page Count */
            page_count: number;
            /** Platform */
            platform: string;
            /** Product Count */
            product_count: number;
            /** Source Used */
            source_used: string;
            /** Ssl Bypassed */
            ssl_bypassed: boolean;
            /** Status */
            status: string;
            /** Url */
            url: string;
        };
        /** TrafficCity */
        TrafficCity: {
            /** Cart Sessions */
            cart_sessions: number;
            /** City */
            city: string;
            /** Country */
            country: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "data_center" | "own_team" | "other";
            /** Sessions */
            sessions: number;
        };
        /** TrafficMinute */
        TrafficMinute: {
            /** Minute */
            minute: string;
            /** Sessions */
            sessions: number;
        };
        /** TrafficPage */
        TrafficPage: {
            /** Cart Sessions */
            cart_sessions: number;
            /** Path */
            path: string;
            /** Sessions */
            sessions: number;
        };
        /** TrafficPoint */
        TrafficPoint: {
            /** At */
            at: string;
            /** Sessions */
            sessions: number;
        };
        /** TrafficQuota */
        TrafficQuota: {
            /** Available */
            available: number;
            /** Maximum */
            maximum: number;
            /** Resets At */
            resets_at: string;
        };
        /** TrafficShare */
        TrafficShare: {
            /** Name */
            name: string;
            /** Sessions */
            sessions: number;
        };
        /** TrafficSnapshot */
        TrafficSnapshot: {
            /** Breakdown At */
            breakdown_at: string;
            /** Cities */
            cities: components["schemas"]["TrafficCity"][];
            /** Data Center Sessions */
            data_center_sessions: number;
            /** Devices */
            devices: components["schemas"]["TrafficShare"][];
            /** Minutes */
            minutes: components["schemas"]["TrafficMinute"][];
            /** Minutes At */
            minutes_at: string;
            /** Pages */
            pages: components["schemas"]["TrafficPage"][];
            /**
             * Period
             * @enum {string}
             */
            period: "1h" | "24h" | "7d";
            /**
             * Problem
             * @enum {string}
             */
            problem: "" | "quota_low" | "unreachable" | "auth_failed" | "query_failed";
            quota: components["schemas"]["TrafficQuota"] | null;
            /** Series */
            series: components["schemas"]["TrafficPoint"][];
            /**
             * Series Grain
             * @enum {string}
             */
            series_grain: "minute" | "hour";
            /** Shop */
            shop: string;
            /** Sources */
            sources: components["schemas"]["TrafficShare"][];
            totals: components["schemas"]["TrafficTotals"];
        };
        /** TrafficTotals */
        TrafficTotals: {
            /** Cart Sessions */
            cart_sessions: number;
            /** Checkout Sessions */
            checkout_sessions: number;
            /** Sessions */
            sessions: number;
        };
        /** UploadOut */
        UploadOut: {
            /** Filename */
            filename: string;
            /** Size Bytes */
            size_bytes: number;
            /** Upload Id */
            upload_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    detection_view_api_detection_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectionOut"];
                };
            };
        };
    };
    start_discovery_api_discover_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscoverIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discover_options_api_discover_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverOptionsOut"];
                };
            };
        };
    };
    discovery_api_discover__discovery_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                discovery_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    llm_check_api_llm_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LLMCheckIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMCheckOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    llm_providers_api_llm_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderOut"][];
                };
            };
        };
    };
    options_api_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptionsOut"];
                };
            };
        };
    };
    overview_api_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewOut"];
                };
            };
        };
    };
    preview_api_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_api_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListItem"][];
                };
            };
        };
    };
    create_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_detail_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_api_runs__run_id__download__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_events_api_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_run_api_runs__run_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rows_api_runs__run_id__rows__table__get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                include_raw?: boolean;
            };
            header?: never;
            path: {
                run_id: string;
                table: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RowsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_run_api_runs__run_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    traffic_view_api_traffic_get: {
        parameters: {
            query?: {
                period?: "1h" | "24h" | "7d";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrafficSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_api_uploads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_api_uploads_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
