/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Options */
        get: operations["options_api_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview */
        post: operations["preview_api_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs */
        get: operations["runs_api_runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Detail */
        get: operations["run_detail_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/download/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download */
        get: operations["download_api_runs__run_id__download__key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Events
         * @description Server-sent events: the full run state each time it changes, until it ends.
         */
        get: operations["run_events_api_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/full": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Full Run
         * @description Run the whole list of a finished test run, with the same input and formats.
         */
        post: operations["full_run_api_runs__run_id__full_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume Run
         * @description Continue a stopped or interrupted run without revisiting finished stores.
         */
        post: operations["resume_run_api_runs__run_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/rows/{table}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rows */
        get: operations["rows_api_runs__run_id__rows__table__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop Run
         * @description Finish the stores in progress, start no new ones; the run stays resumable.
         */
        post: operations["stop_run_api_runs__run_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload */
        post: operations["upload_api_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_api_uploads_post */
        Body_upload_api_uploads_post: {
            /** File */
            file: string;
        };
        /** DownloadOut */
        DownloadOut: {
            /** Filename */
            filename: string;
            /** Key */
            key: string;
            /** Label */
            label: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** OptionsOut */
        OptionsOut: {
            /** Default Test Limit */
            default_test_limit: number;
            /** Default Writers */
            default_writers: string[];
            /** Max Links */
            max_links: number;
            /** Max Upload Mb */
            max_upload_mb: number;
            /** Suffixes */
            suffixes: string[];
            /** Writers */
            writers: string[];
        };
        /** OverviewOut */
        OverviewOut: {
            /** Contacts */
            contacts: number;
            last_run: components["schemas"]["RunListItem"] | null;
            /** Products */
            products: number;
            /** Runs */
            runs: number;
            /** Runs Done */
            runs_done: number;
            /** Stores */
            stores: number;
        };
        /** PreviewIn */
        PreviewIn: {
            source: components["schemas"]["SourceIn"];
            /**
             * Url Column
             * @default auto
             */
            url_column: string;
        };
        /** PreviewOut */
        PreviewOut: {
            /** Duplicates */
            duplicates: number;
            /** Links */
            links: number;
            /** Max Links */
            max_links: number;
            /** Skipped */
            skipped: {
                [key: string]: number;
            };
            /** Skipped Examples */
            skipped_examples: components["schemas"]["SkippedLink"][];
            /** Store Examples */
            store_examples: string[];
            /** Stores */
            stores: number;
            /** Tested */
            tested: boolean;
            /** Too Many */
            too_many: boolean;
        };
        /**
         * RowsOut
         * @description A page of one table's rows, for previewing data in the interface.
         */
        RowsOut: {
            /** Columns */
            columns: string[];
            /** Offset */
            offset: number;
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
            /** Table */
            table: string;
            /** Total */
            total: number;
            /** Truncated Fields */
            truncated_fields: boolean;
        };
        /** RunIn */
        RunIn: {
            /**
             * Skip Test Run
             * @default false
             */
            skip_test_run: boolean;
            source: components["schemas"]["SourceIn"];
            /**
             * Test Limit
             * @default 2
             */
            test_limit: number;
            /**
             * Test Mode
             * @default true
             */
            test_mode: boolean;
            /**
             * Url Column
             * @default auto
             */
            url_column: string;
            /** Writers */
            writers: string[];
        };
        /** RunListItem */
        RunListItem: {
            /** Contacts */
            contacts: number;
            /** Links In */
            links_in: number;
            /**
             * Mode
             * @enum {string}
             */
            mode: "test" | "full";
            /** Products */
            products: number;
            /** Run Id */
            run_id: string;
            /** Source Name */
            source_name: string;
            /** Started At */
            started_at: string;
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "running" | "stopped" | "done" | "failed" | "interrupted";
            /** Stores Done */
            stores_done: number;
            /** Stores Total */
            stores_total: number;
        };
        /** RunOut */
        RunOut: {
            /** Cli */
            cli: string;
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Contacts */
            contacts: number;
            /** Downloads */
            downloads: components["schemas"]["DownloadOut"][];
            /** Error */
            error: string;
            /** Finished At */
            finished_at: string;
            /** Limit */
            limit: number | null;
            /** Links In */
            links_in: number;
            /**
             * Mode
             * @enum {string}
             */
            mode: "test" | "full";
            /** Pages */
            pages: number;
            /** Processed */
            processed: number;
            /** Products */
            products: number;
            /** Run Id */
            run_id: string;
            /** Skipped */
            skipped: number;
            /** Skipped By Reason */
            skipped_by_reason: {
                [key: string]: number;
            };
            /**
             * Source Kind
             * @enum {string}
             */
            source_kind: "text" | "file";
            /** Source Name */
            source_name: string;
            /** Started At */
            started_at: string;
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "running" | "stopped" | "done" | "failed" | "interrupted";
            /** Status Counts */
            status_counts: {
                [key: string]: number;
            };
            /** Stores */
            stores: components["schemas"]["StoreOut"][];
            /** Stores Done */
            stores_done: number;
            /** Stores Total */
            stores_total: number;
            /** Writers */
            writers: string[];
        };
        /** SkippedLink */
        SkippedLink: {
            /** Raw */
            raw: string;
            /** Reason */
            reason: string;
        };
        /**
         * SourceIn
         * @description Exactly one of pasted text or a previously uploaded file.
         */
        SourceIn: {
            /** Text */
            text?: string | null;
            /** Upload Id */
            upload_id?: string | null;
        };
        /** StoreOut */
        StoreOut: {
            /** Contact Count */
            contact_count: number;
            /** Currency */
            currency: string;
            /** Domain */
            domain: string;
            /** Error */
            error: string;
            /** Page Count */
            page_count: number;
            /** Platform */
            platform: string;
            /** Product Count */
            product_count: number;
            /** Source Used */
            source_used: string;
            /** Ssl Bypassed */
            ssl_bypassed: boolean;
            /** Status */
            status: string;
            /** Url */
            url: string;
        };
        /** UploadOut */
        UploadOut: {
            /** Filename */
            filename: string;
            /** Size Bytes */
            size_bytes: number;
            /** Upload Id */
            upload_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    options_api_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptionsOut"];
                };
            };
        };
    };
    overview_api_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewOut"];
                };
            };
        };
    };
    preview_api_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_api_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListItem"][];
                };
            };
        };
    };
    create_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_detail_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_api_runs__run_id__download__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_events_api_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    full_run_api_runs__run_id__full_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_run_api_runs__run_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rows_api_runs__run_id__rows__table__get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                include_raw?: boolean;
            };
            header?: never;
            path: {
                run_id: string;
                table: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RowsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_run_api_runs__run_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_api_uploads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_api_uploads_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
